echo SolarSoft setup/startup file Revision 1.0
echo Generated by WWW/ssw_install at: Thu Nov 25 08:11:22 2010
echo .

set HOST=lmsal.com
rem Define the location of SolarSoft, SSWDB and the Windows startup
set SSW=C:\ssw
set SSWDB=C:\sswdb
set IDL_STARTUP=C:\ssw\gen\idl\ssw_system\idl_startup_windows.pro

rem A personal startup can be defined by editing the following statement
set SSW_PERSONAL_STARTUP=c:\IDLcodes\idl_startup.pro

rem   A default set of instruments be defined by editing the following
set SSW_INSTR=ethz norp nrh ovsa sxig12 sxig13 goes

rem Optional Instrument specific setup/startup

rem   If you are not using the default version of IDL, add a path below

cd C:\Program Files\ITT\IDL71\idlde
start idl C:\MyIDLcodes\email_warning_batch

